spring.application.name=backend
server.port=8080

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=
spring.data.mongodb.database=attendance_db

# SMS Provider (twilio or fast2sms)
sms.provider=twilio
sms.enabled=true

twilio.account.sid=
twilio.auth.token=
twilio.phone.number=



# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
