spring.application.name=backend
server.port=8080

# Load environment variables from .env file
spring.config.import=optional:file:.env[.properties]

# MongoDB
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

# Flask Face Recognition Service
face.api.url=${FACE_API_URL:https://attendence-system-zg1v.onrender.com}
